[[plugins]]
repo = 'davidhalter/jedi-vim'
on_event = 'InsertEnter'
on_ft = 'python'
hook_add = '''
let g:jedi#force_py_version = 3
let g:jedi#completions_enabled = 0
'''

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = 'python'
